### ISSUE TITLE
unable to deploy on OKD

### ISSUE THREAD

**Issue by clopnis** [grycap/im#1467]
As OKD is using Route to expose service, helm fail to deploy even Ingress are set as enabled: false

```
helm install --namespace=grycap im grycap/IM -f values.yaml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "im-dashboard" namespace: "" from "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "im" namespace: "" from "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "im-web" namespace: "" from "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
ensure CRDs are installed first]
```
values.yaml
```
imweb:
  deploy: true
  version: latest
  image: grycap/im-web
  ingress:
    enabled: false
[...]
imdashboard:
  deploy: true
  image: grycap/im-dashboard
  version: latest
  ingress:
    enabled: false
[...]
im:
  version: latest
  image: grycap/im
  ingress:
    enabled: false
```
