### ISSUE TITLE
Evaluate Mitogen

### ISSUE THREAD

**Issue by micafer** [grycap/im#708]
https://mitogen.readthedocs.io/en/stable/ansible.html

**Comment by micafer** [comment]
Mitogen can be activated adding this lines to the conf-ansible.yml file:

```
    - block:

        - name: Download mitogen
          unarchive:
            src: https://networkgenomics.com/try/mitogen-0.2.8.tar.gz
            dest: /usr/local
            remote_src: yes

        - name: Set strategy_plugins ansible.cfg var
          ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=strategy_plugins value=/usr/local/mitogen-0.2.8/ansible_mitogen/plugins/strategy

        - name: Set strategy ansible.cfg var
          ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=strategy value=mitogen_linear
```
